### PR TITLE
[WIP] Adds ffi-libarchive for interacting with libarchive under the hood.

### PR DESCRIPTION
**Pull request by johnbellone**
/cc @reset 

These commits add support for using [ffi-libarchive Ruby library](https://github.com/johnbellone/ffi-libarchive) instead of the [libarchive-ruby extension](https://github.com/Hanmac/libarchive-ruby). The main result here is that we no longer need to install build-essentials. There were a few hiccups and I've separately [forked the ffi-libarchive Ruby library](https://github.com/johnbellone/ffi-libarchive-cookbook) and prepared it to distribute as a Chef cookbook. I am reaching out to the maintainer to see if he will accept the changes.

This covers a few issues in the Consul cookbook which were consolidated into [CONSUL-169](https://github.com/johnbellone/consul-cookbook/issues/169).

### CODE REVIEW

**Comment by johnbellone** [comment]
I still have a lot of testing to do here, but the majority of it is there. I should have time this week to continue to work.

**Comment by johnbellone** [comment]
I spoke with author of ffi-libarchive and he transferred stewardship over to myself. Added @reset as collaborator.

**Comment by reset** [comment]
@johnbellone some of the links in the issue are broken. What are the changes required for the libarchive gem? Did you already finish them up in your fork (now mainline)?

**Comment by johnbellone** [comment]
@reset Yeah, the changes are finished on [my fork](https://github.com/johnbellone/ffi-libarchive).

**Comment by reset** [comment]
@johnbellone sorry that this fell off my radar. So to be clear - this PR is complete with no behaviour changes?

**Comment by johnbellone** [comment]
@reset That is the intention, but test cases were a little sparse. Anything in particular I should test?

**Comment by reset** [comment]
@johnbellone no, I think this is good to go. I'll merge in and give it some testing

**Pull request merged**
