### PR TITLE
bumping apt contraint, fixing serverspec test

### PR DESCRIPTION
**Pull request by majormoses**

### CODE REVIEW

**Comment by hatchetation** [comment]
This change is especially valuable because it would allow for use of the apt cookbook 4.0, which has been modified to better support chef 12.9's new built-in `apt_repository` resource.

**Comment by majormoses** [comment]
@reset any chance of getting this merged? @hatchetation you can use my fork in the meantime...

**Comment by davidsayers** [comment]
👍 the constraint is causing problems in other cookbooks

**Comment by reset** [comment]
@majormoses sure, we can merge the changes here. I just need you to correct the version field of the metadata file. Please don't bump the version number in PRs ;)

**Comment by majormoses** [comment]
@reset as requested I removed the version bump.

**Comment by majormoses** [comment]
@reset any chance we can get a version bump and supermarket release?

**Pull request merged**
